package com.androidprj.fuzic.ui.theme

import androidx.compose.ui.graphics.Color

val MidnightViolet = Color(0xFF7C4DFF)
val ElectricTeal = Color(0xFF00C2A8)
val PremiumGold = Color(0xFFF5B84B)
val OnDarkAccent = Color(0xFFFFFFFF)
val OnDarkPrimary = Color(0xFF381E72)
val OnDarkSecondary = Color(0xFF003731)
val OnGold = Color(0xFF271900)

val MidnightVioletLight = Color(0xFF5E35D8)
val MidnightVioletContainerLight = Color(0xFFE9DDFF)
val OnMidnightVioletContainerLight = Color(0xFF21005D)
val ElectricTealLight = Color(0xFF006D62)
val ElectricTealContainerLight = Color(0xFF79F8E3)
val OnElectricTealContainerLight = Color(0xFF00201C)
val PremiumGoldLight = Color(0xFF795900)
val PremiumGoldContainerLight = Color(0xFFFFDEA6)
val OnPremiumGoldContainerLight = Color(0xFF261900)
val MidnightErrorLight = Color(0xFFBA1A1A)
val MidnightBackgroundLight = Color(0xFFFEF9FF)
val MidnightSurfaceLight = Color(0xFFFEF9FF)
val MidnightSurfaceVariantLight = Color(0xFFE7E0EF)
val OnMidnightSurfaceVariantLight = Color(0xFF49454F)
val MidnightOutlineLight = Color(0xFF79747E)
val MidnightOnLight = Color(0xFF1D1A22)

val MidnightVioletDark = Color(0xFFD0BCFF)
val ElectricTealDark = Color(0xFF4FDCC9)
val PremiumGoldDark = Color(0xFFFFD98A)
val MidnightErrorDark = Color(0xFFFFB4AB)
val MidnightBackgroundDark = Color(0xFF111018)
val MidnightSurfaceDark = Color(0xFF111018)
val MidnightSurfaceVariantDark = Color(0xFF49454F)
val OnMidnightSurfaceVariantDark = Color(0xFFCAC4D0)
val MidnightOutlineDark = Color(0xFF938F99)
val MidnightOnDark = Color(0xFFE8E0EE)
